[project]
name = "anno-117-optimizer"
version = "0.1.0"
description = "Anno 117 Optimizer"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pydantic>=2.12.4",
    "pyyaml>=6.0.3",
]
